services:

  star-wars-backend:
    image: star-wars-backend
    build: 
      context: ./star-wars-backend
    container_name: STAR-WARS-BACKEND
    volumes:
      - ./backend:/usr/src/app
    restart: always
    environment:
      - MONGODB_USER=rafikbensadi
      - MONGODB_PASSWORD=qMNiOQbE8sgznUba
      - PORT=8000
      - TOKEN=iRFSkLbscB63tzd3m0QJEFvAd8Iu1VGizxtmkXqLQkcTt10twcigFYE9EZdGuMsgmkLjcBGjkfZ72aZ6xeZJ0C8DmIdXSWdEeAcCfuKIAc4DC0GHZ1vIkvckUdFAD4M
      - API_KEY=41c45185-a5f9-44d0-b12a-5b70a7bc5b88:fx
      - NB_HASH=10
    ports:
      - 8000:8000

  
  star-wars-blog:
    image: star-wars-blog
    build:
      context: ./star-wars-blog
    container_name: STAR-WARS-BLOG
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - star-wars-backend
    ports: 
      - 3000:3000